# Generated by Django 5.0.1 on 2024-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
