# Generated by Django 5.0.1 on 2024-01-11 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
