# Generated by Django 5.0.1 on 2024-02-02 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_userdetails_email_userdetails_mobile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdetails',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
