# Generated by Django 5.0.1 on 2024-02-02 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_rename_name_userdetails_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='location',
            field=models.TextField(blank=True, null=True),
        ),
    ]
