# Generated by Django 5.0.1 on 2024-02-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0007_alter_userdetails_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
